#!/bin/bash

set -eux

HOST_DEV_DIR=${HOST_DEV_DIR:-/mnt/host-dev}
LOG_LEVEL=${LOG_LEVEL:-INFO}

if [ -c "${HOST_DEV_DIR}/zero" ] && [ -c "${HOST_DEV_DIR}/null" ]; then
    # looks like an alternate "host dev" has been provided
    # to the container. Use that as our /dev ongoing
    mount --rbind "${HOST_DEV_DIR}" /dev
fi

/lib/systemd/systemd-udevd & UDEVD_PID=$!

HEKETI_CUSTOM_FSTAB=${HEKETI_CUSTOM_FSTAB:-/var/lib/heketi/fstab}
if [ -f $HEKETI_CUSTOM_FSTAB ]; then
      pvscan
      vgscan
      lvscan
      vgchange -an

      pvscan
      vgscan
      lvscan
      vgchange -ay

      mount -a --fstab $HEKETI_CUSTOM_FSTAB
      sts=$?
      if [ $sts -eq 0 ]; then
            echo "Mount command Successful"

            mount --bind $HEKETI_CUSTOM_FSTAB /etc/fstab

            touch $HEKETI_CUSTOM_FSTAB.save
            mount --bind $HEKETI_CUSTOM_FSTAB.save /etc/fstab.save
      fi
fi

kill SIGINT $UDEVD_PID
wait $UDEVD_PID
