[globals]
gluster-mgmt = "glusterd"
glusterd-dir = "/var/lib/glusterd"
gluster-binary-path = "gluster"
gd1-remote-host = "localhost"
port = 24100
metrics-path = "/metrics"
log-dir = "/var/log"
log-file = "gluster-exporter.log"
log-level = "info"
cache-ttl-in-sec = 60
cache-enabled-funcs = [ 'IsLeader', 'LocalPeerID', 'HealInfo', 'VolumeInfo' ]

[collectors.gluster_ps]
name = "gluster_ps"
sync-interval = 15
disabled = false

[collectors.gluster_brick]
name = "gluster_brick"
sync-interval = 15
disabled = false

[collectors.gluster_brick_status]
name = "gluster_brick_status"
sync-interval = 15
disabled = false

[collectors.gluster_peer_counts]
name = "gluster_peer_counts"
sync-interval = 15
disabled = false

[collectors.gluster_peer_info]
name = "gluster_peer_info"
sync-interval = 15
disabled = false

[collectors.gluster_volume_profile]
name = "gluster_volume_profile"
sync-interval = 15
disabled = false

[collectors.gluster_volume_counts]
name = "gluster_volume_counts"
sync-interval = 15
disabled = false

[collectors.gluster_volume_status]
name = "gluster_volume_status"
sync-interval = 15
disabled = false
